export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_OPEN_MODAL = 'USER_OPEN_MODAL';
export const USER_CLOSE_MODAL = 'USER_CLOSE_MODAL';
